version: '3.1'
volumes:
  horde-db:
  horde-turba:
  horde-nag:
  horde-ingo:
  horde-mnemo:
  horde-horde:
  horde-imp:
  horde-kronolith:
services:
  horde:
    build: .
    environment:
      HORDE_SQL_USERNAME: root
      HORDE_SQL_PASSWORD: pass
      HORDE_SQL_HOST: db
      HORDE_SQL_DATABASE: horde
      IMP_HOSTSPEC: imap.myserver
      IMP_MAILDOMAIN: my.maildomain
      INGO_SIEVE_HOST: mysieve.server
      INGO_SIEVE_USETLS: 'false'
      HORDE_THEME: 'knttheme'
      HORDE_THEME_LOCKED: 'true'
    restart: on-failure
    links:
      - db
      - memcached
    ports:
      - "80:80"
    volumes:
    - horde-turba:/var/www/html/horde/turba/config
    - horde-nag:/var/www/html/horde/nag/config
    - horde-ingo:/var/www/html/horde/ingo/config
    - horde-mnemo:/var/www/html/horde/mnemo/config
    - horde-horde:/var/www/html/horde/config
    - horde-imp:/var/www/html/horde/imp/config
    - horde-kronolith:/var/www/html/horde/kronolith/config
  memcached:
    image: memcached:1.5-alpine
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: horde
    command: --max_allowed_packet=32505856
    volumes:
      - horde-db:/var/lib/mysql

